/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.junior.dados2;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author jr
 */
public class Dados2 extends javax.swing.JFrame {

    /**
     * Creates new form Dados2
     */
    public Dados2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClick = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblClick.setText("GIre o dado!!!");
        lblClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblClickActionPerformed(evt);
            }
        });

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setText("GIre o dado!!");
        lblImagem.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblImagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblClick))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblClick)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblClickActionPerformed
        // TODO add your handling code here:
        double ale = Math.random();
        int giroDados = (int) (1 + ale * 6);
         lblImagem.setText("");
               
        switch (giroDados){
            case 1 -> {
                ImageIcon dado = new ImageIcon(new ImageIcon("C:/Users/jr/Pictures/dados_img/dado1.jpg").getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
                lblImagem.setIcon(dado); 
            }
            case 2 -> {
                ImageIcon dado2 = new ImageIcon(new ImageIcon("C:/Users/jr/Pictures/dados_img/dado2.jpg").getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
                lblImagem.setIcon(dado2);
            }
            case 3 -> {
                ImageIcon dado3 = new ImageIcon(new ImageIcon("C:/Users/jr/Pictures/dados_img/dado3.jpg").getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
                lblImagem.setIcon(dado3);
            }
            case 4 -> {
                ImageIcon dado4 = new ImageIcon(new ImageIcon("C:/Users/jr/Pictures/dados_img/dado4.jpg").getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
                lblImagem.setIcon(dado4);
            }
            case 5 -> {
                ImageIcon dado5 = new ImageIcon(new ImageIcon("C:/Users/jr/Pictures/dados_img/dado5.jpg").getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
                lblImagem.setIcon(dado5) ;
            }
            default -> {
                ImageIcon dado6 = new ImageIcon(new ImageIcon("C:/Users/jr/Pictures/dados_img/dado6.jpg").getImage().getScaledInstance(100,100,Image.SCALE_DEFAULT));
                lblImagem.setIcon(dado6); 
                        }
        }
       
        System.out.println(giroDados);
    }//GEN-LAST:event_lblClickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dados2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lblClick;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
