/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cursoemvideo.votanaovota;

/**
 *
 * @author jr
 */
public class TelaVota extends javax.swing.JFrame {

    /**
     * Creates new form TelaVota
     */
    
    int anoAtual = 2022;
    
    public TelaVota() {
        initComponents();
        lblAnoAtualPrinc.setText(Integer.toString(anoAtual));
              
        pnlMudaAno.setVisible(false);
        pnlSituacaoVoto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnVerificar = new javax.swing.JButton();
        lblAnoAtualPrinc = new javax.swing.JLabel();
        btnMudaAno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNasc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlMudaAno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAlterarAno = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblAnoAtual = new javax.swing.JLabel();
        txtNovoAno = new javax.swing.JTextField();
        pnlSituacaoVoto = new javax.swing.JPanel();
        lblSituacaoVoto = new javax.swing.JLabel();
        btnVoltaPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        btnVerificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        lblAnoAtualPrinc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnoAtualPrinc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnoAtualPrinc.setText("0");
        lblAnoAtualPrinc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnoAtualPrinc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnMudaAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMudaAno.setText("Mudar Ano");
        btnMudaAno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMudaAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMudaAnoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Data de Nascimento");

        txtNasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNasc.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ano Atual");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Situação Eleitoral");
        jLabel3.setAlignmentY(0.0F);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAnoAtualPrinc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMudaAno)
                .addGap(46, 46, 46))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txtNasc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAnoAtualPrinc)
                    .addComponent(btnMudaAno))
                .addGap(51, 51, 51)
                .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ano Atual");

        btnAlterarAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlterarAno.setText("Alterar");
        btnAlterarAno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterarAno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterarAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAnoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Digite Novo Ano");

        lblAnoAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnoAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNovoAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNovoAno.setText("0");

        javax.swing.GroupLayout pnlMudaAnoLayout = new javax.swing.GroupLayout(pnlMudaAno);
        pnlMudaAno.setLayout(pnlMudaAnoLayout);
        pnlMudaAnoLayout.setHorizontalGroup(
            pnlMudaAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMudaAnoLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnAlterarAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMudaAnoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlMudaAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(pnlMudaAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNovoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pnlMudaAnoLayout.setVerticalGroup(
            pnlMudaAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMudaAnoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnlMudaAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMudaAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnAlterarAno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblSituacaoVoto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSituacaoVoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSituacaoVoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVoltaPrincipal.setText("OK");
        btnVoltaPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSituacaoVotoLayout = new javax.swing.GroupLayout(pnlSituacaoVoto);
        pnlSituacaoVoto.setLayout(pnlSituacaoVotoLayout);
        pnlSituacaoVotoLayout.setHorizontalGroup(
            pnlSituacaoVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSituacaoVotoLayout.createSequentialGroup()
                .addGroup(pnlSituacaoVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSituacaoVotoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSituacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSituacaoVotoLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnVoltaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSituacaoVotoLayout.setVerticalGroup(
            pnlSituacaoVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSituacaoVotoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblSituacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnVoltaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMudaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlSituacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMudaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlSituacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        int nasc = Integer.parseInt(txtNasc.getText());
        int i = anoAtual - nasc;
        
        if (i >= 16  &&  i < 18  ||  i > 70) {
            lblSituacaoVoto.setText("<html>sua idade é " + i + " e seu Voto é Opcional.</html>");
        } else if (i<16){
            lblSituacaoVoto.setText("<html>Vocé é menor de idade e não poderá Votar!</html>");
        } else {
            lblSituacaoVoto.setText("<html>Sua idade é "+i+" e seu voto é obrigatório!</html>");
        }
        pnlPrincipal.setVisible(false);
        pnlSituacaoVoto.setVisible(true);
    }                                            

    private void btnMudaAnoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         pnlPrincipal.setVisible(false);
         pnlMudaAno.setVisible(true);
         lblAnoAtual.setText(Integer.toString(anoAtual));
         
       
        
        
    }                                          

    private void btnVoltaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        pnlPrincipal.setVisible(true);
        pnlSituacaoVoto.setVisible(false);
        lblAnoAtualPrinc.setText(Integer.toString(anoAtual));
        lblAnoAtual.setText(Integer.toString(anoAtual));
    }                                                 

    private void btnAlterarAnoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        anoAtual = Integer.parseInt(txtNovoAno.getText());
        lblSituacaoVoto.setText(String.format("O novo ano é " + anoAtual));
        pnlMudaAno.setVisible(false);
        pnlSituacaoVoto.setVisible(true);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAlterarAno;
    private javax.swing.JButton btnMudaAno;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnVoltaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAnoAtual;
    private javax.swing.JLabel lblAnoAtualPrinc;
    private javax.swing.JLabel lblSituacaoVoto;
    private javax.swing.JPanel pnlMudaAno;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSituacaoVoto;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNovoAno;
    // End of variables declaration                   
}
